### ISSUE TITLE
Creation of ViewController in Test case can be improved

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#1]
https://github.com/adarsh-a-tw/BullsEye/blob/ccb45eeddb15c3877f8ab5ee2e69e1fb0dbe5cc3/BullsEyeTests/BullsEyeTests.swift#L22

`GameViewController` can be initialised in better way. google how to create instance of a view controller from a storyboard

Once it done, you may not require to manually create all the UI element (as like the below) & set it to `sut`
```
    let slider = UISlider()
    let roundLabel = UILabel()
    let scoreLabel = UILabel()
    let targetLabel = UILabel()
```

**Comment by adarsh-a-tw** [comment]
Refactored as per suggestion
