### ISSUE TITLE
Suggestion: Split the function further 

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#2]
https://github.com/adarsh-a-tw/BullsEye/blob/ccb45eeddb15c3877f8ab5ee2e69e1fb0dbe5cc3/BullsEye/ViewControllers/GameViewController.swift#L32

You are doing two things in this function
1. Checking the guessed value
2. Showing Alert

**Comment by adarsh-a-tw** [comment]
Refactored as per suggestion.
