### ISSUE TITLE
General Feedback on Codebase

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#3]
Great job Adarsh. You accommodated almost all the suggestion which we gave on 6th Sept 2022

1. Created folders & moved files accordingly
2. Moved the slider image setup into separate function
3. Moved `MockBullsEyeGame` into appropriate target & folder
4. Corrected safe area of background image

**Happy to see that** 
* you introduced a protocol for your business logic class & mocking it in test cases
* you are writing test cases. that too, you are covering more cases. 
* the app is working seamlessly
* you added App Icon
* you added meaningful app name & bundle id
* you added gitignore
* folder & file structure is good

Keep up the good work Adarsh

**Comment by adarsh-a-tw** [comment]
Thank you for the feedback
