### ISSUE TITLE
`testStartNewGame` will fail if random give 50 in return

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#4]
https://github.com/adarsh-a-tw/BullsEye/blob/ccb45eeddb15c3877f8ab5ee2e69e1fb0dbe5cc3/BullsEyeGameTests/BullsEyeGameTests.swift#L26

`testStartNewGame` will fail if random give 50 in return

**Comment by adarsh-a-tw** [comment]
Please refer #5 for more details
