### ISSUE TITLE
`testStartNewRound` will fail if random give exact same number as previous

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#5]
https://github.com/adarsh-a-tw/BullsEye/blob/ccb45eeddb15c3877f8ab5ee2e69e1fb0dbe5cc3/BullsEyeGameTests/BullsEyeGameTests.swift#L36

`testStartNewRound` will fail if random give exact same number as previous

**Comment by adarsh-a-tw** [comment]
I have fixed issues #4 and #5 by adding a new stub class. 

@shebin-tw  Please let me know if this approach needs improvements.
