### ISSUE TITLE
Suggestion: Improve the readability of `testShouldCheckGuessAndDisplayAlert` test case

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#6]
https://github.com/adarsh-a-tw/BullsEye/blob/ccb45eeddb15c3877f8ab5ee2e69e1fb0dbe5cc3/BullsEyeTests/BullsEyeTests.swift#L56

I didn't understand the `SideEffect` naming in `checkAndUpdateScoreMethodSideEffect`.

**Point 2**
https://github.com/adarsh-a-tw/BullsEye/blob/ccb45eeddb15c3877f8ab5ee2e69e1fb0dbe5cc3/BullsEyeTests/BullsEyeTests.swift#L63
 It will be easy to understand, if `[1]` can be put in a variable with proper naming.

**Comment by adarsh-a-tw** [comment]
I have renamed the variable name as per suggestion. I previously used the term SideEffect  because of the naming convention used in python unit testing. Side effect generally refers to an action that needs to be performed or a value returned by a function. 

I have also made the test more readable

**Comment by shebin-tw** [comment]
Thanks for sharing reason behind the term SideEffect
