### ISSUE TITLE
Suggestion: Can we remove result tuple from showAlert function params

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#7]
https://github.com/adarsh-a-tw/BullsEye/blob/44f2ac7a1a1f20c151d20136a145bf405e191717/BullsEye/ViewControllers/GameViewController.swift#L74

Can we remove result tuple from showAlert function params?

**Suggestion 2:**
Can we take out `self.startNewRound()` from alert function? I mean by introducing an action closure in showAlert function?
https://github.com/adarsh-a-tw/BullsEye/blob/44f2ac7a1a1f20c151d20136a145bf405e191717/BullsEye/ViewControllers/GameViewController.swift#L77

**Comment by adarsh-a-tw** [comment]
Refactored as per suggestions
