### ISSUE TITLE
Seems like you forgot to connect the integer generator with actual code

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#8]
https://github.com/adarsh-a-tw/BullsEye/blob/44f2ac7a1a1f20c151d20136a145bf405e191717/BullsEye/Models/BullsEyeGame.swift#L26

Seems like you forgot to connect the integer generator with `Int.random(in: 1...100)`

**Comment by adarsh-a-tw** [comment]
Yes, I have resolved it now. Thanks for pointing it out.
