### ISSUE TITLE
Suggesting to move business logics from model class to a new controller class

### ISSUE THREAD

**Issue by shebin-tw** [adarsh-a-tw/BullsEye#9]
Suggesting to move the below functions to a new controller class. 

https://github.com/adarsh-a-tw/BullsEye/blob/44f2ac7a1a1f20c151d20136a145bf405e191717/BullsEye/Models/BullsEyeGame.swift#L18

https://github.com/adarsh-a-tw/BullsEye/blob/44f2ac7a1a1f20c151d20136a145bf405e191717/BullsEye/Models/BullsEyeGame.swift#L24

https://github.com/adarsh-a-tw/BullsEye/blob/44f2ac7a1a1f20c151d20136a145bf405e191717/BullsEye/Models/BullsEyeGame.swift#L30

Model can have the below variables

```
    var score:Int = 0
    var round:Int = 0
    var targetValue:Int = 50
```

**Comment by adarsh-a-tw** [comment]
Refactored as per suggestion
